# Generated by Django 4.0.5 on 2022-06-08 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='book', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь книги'),
        ),
    ]
