# Generated by Django 4.0.5 on 2022-06-19 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('exp', models.CharField(max_length=100)),
                ('iat', models.CharField(max_length=100)),
                ('jti', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
