# Generated by Django 4.0.5 on 2022-06-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jwtokens',
            old_name='user_id',
            new_name='user',
        ),
    ]
